#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - develop

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - doc/*
#    - '**/*.html'

# Maximum number of concurrent jobs for the project
max_jobs: 1

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - git config --global core.autocrlf input

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\safe_numerics

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several configurations to build matrix:
configuration:
  - Debug
  # - Release

# scripts to run before build
before_build:
  - cmd: cd C:\projects\safe_numerics
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" ..

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: cd C:\projects\safe_numerics\build
  - cmd: nmake /f makefile


# to disable automatic builds
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - cmd: cd C:\projects\safe_numerics\build
  - cmd: nmake /f makefile test

# to disable automatic tests
test: off

