#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

shallow_clone: true

# branches to build
branches:
  # whitelist
  only:
    - develop

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - doc/*
    - doc/html/*'

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/config
  - git submodule init libs/concept_check
  - git submodule init libs/mpl
  - git submodule init libs/preprocessor
  - git submodule init libs/logic
  - git submodule update
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\safe_numerics\
  - bootstrap
  - b2 headers

build: off

test_script:
  - b2 libs/safe_numerics/test toolset=msvc-14.0
